import type { Region } from "../types";

// AWS: sts.<region>.amazonaws.com returns 302 for unauthenticated requests.
// With redirect:"manual" the browser stops before the redirect and returns an opaque-redirect
// response (status 0). Chrome logs nothing to the DevTools console.
//
// GCP: Cloud Run instances maintained by Google DevRel (gcping.com, Apache-2 licensed,
// https://github.com/GoogleCloudPlatform/gcping). Returns 200, fetched with no-cors.
// URLs snapshotted 2026-08-20 from https://global.gcping.com/api/endpoints.
// If these start timing out after a GCP redeployment, re-fetch the API and update.
//
// Cloudflare: speed.cloudflare.com/__down?bytes=0, anycast, always hits the nearest PoP.

export const REGIONS: Region[] = [
  // AWS
  {
    id: "aws-us-east-1",
    provider: "aws",
    city: "N. Virginia",
    country: "US",
    lat: 38.9,
    lon: -77.5,
    endpoint: "https://sts.us-east-1.amazonaws.com",
  },
  {
    id: "aws-us-east-2",
    provider: "aws",
    city: "Ohio",
    country: "US",
    lat: 40.0,
    lon: -82.9,
    endpoint: "https://sts.us-east-2.amazonaws.com",
  },
  {
    id: "aws-us-west-2",
    provider: "aws",
    city: "Oregon",
    country: "US",
    lat: 45.5,
    lon: -122.6,
    endpoint: "https://sts.us-west-2.amazonaws.com",
  },
  {
    id: "aws-ca-central-1",
    provider: "aws",
    city: "Montréal",
    country: "CA",
    lat: 45.5,
    lon: -73.6,
    endpoint: "https://sts.ca-central-1.amazonaws.com",
  },
  {
    id: "aws-eu-west-1",
    provider: "aws",
    city: "Ireland",
    country: "IE",
    lat: 53.3,
    lon: -6.3,
    endpoint: "https://sts.eu-west-1.amazonaws.com",
  },
  {
    id: "aws-eu-west-2",
    provider: "aws",
    city: "London",
    country: "GB",
    lat: 51.5,
    lon: -0.1,
    endpoint: "https://sts.eu-west-2.amazonaws.com",
  },
  {
    id: "aws-eu-central-1",
    provider: "aws",
    city: "Frankfurt",
    country: "DE",
    lat: 50.1,
    lon: 8.7,
    endpoint: "https://sts.eu-central-1.amazonaws.com",
  },
  {
    id: "aws-eu-north-1",
    provider: "aws",
    city: "Stockholm",
    country: "SE",
    lat: 59.3,
    lon: 18.1,
    endpoint: "https://sts.eu-north-1.amazonaws.com",
  },
  {
    id: "aws-eu-south-1",
    provider: "aws",
    city: "Milan",
    country: "IT",
    lat: 45.5,
    lon: 9.2,
    endpoint: "https://sts.eu-south-1.amazonaws.com",
  },
  {
    id: "aws-ap-northeast-1",
    provider: "aws",
    city: "Tokyo",
    country: "JP",
    lat: 35.7,
    lon: 139.7,
    endpoint: "https://sts.ap-northeast-1.amazonaws.com",
  },
  {
    id: "aws-ap-northeast-2",
    provider: "aws",
    city: "Seoul",
    country: "KR",
    lat: 37.6,
    lon: 127.0,
    endpoint: "https://sts.ap-northeast-2.amazonaws.com",
  },
  {
    id: "aws-ap-southeast-1",
    provider: "aws",
    city: "Singapore",
    country: "SG",
    lat: 1.3,
    lon: 103.8,
    endpoint: "https://sts.ap-southeast-1.amazonaws.com",
  },
  {
    id: "aws-ap-southeast-2",
    provider: "aws",
    city: "Sydney",
    country: "AU",
    lat: -33.9,
    lon: 151.2,
    endpoint: "https://sts.ap-southeast-2.amazonaws.com",
  },
  {
    id: "aws-ap-south-1",
    provider: "aws",
    city: "Mumbai",
    country: "IN",
    lat: 19.1,
    lon: 72.9,
    endpoint: "https://sts.ap-south-1.amazonaws.com",
  },
  {
    id: "aws-sa-east-1",
    provider: "aws",
    city: "São Paulo",
    country: "BR",
    lat: -23.5,
    lon: -46.6,
    endpoint: "https://sts.sa-east-1.amazonaws.com",
  },
  {
    id: "aws-af-south-1",
    provider: "aws",
    city: "Cape Town",
    country: "ZA",
    lat: -33.9,
    lon: 18.4,
    endpoint: "https://sts.af-south-1.amazonaws.com",
  },
  {
    id: "aws-me-south-1",
    provider: "aws",
    city: "Bahrain",
    country: "BH",
    lat: 26.2,
    lon: 50.6,
    endpoint: "https://sts.me-south-1.amazonaws.com",
  },

  // GCP (via gcping.com Cloud Run, snapshot 2026-08-20)
  {
    id: "gcp-us-east4",
    provider: "gcp",
    city: "N. Virginia",
    country: "US",
    lat: 38.9,
    lon: -77.5,
    endpoint: "https://us-east4-5tkroniexa-uk.a.run.app",
    noCors: true,
  },
  {
    id: "gcp-us-central1",
    provider: "gcp",
    city: "Iowa",
    country: "US",
    lat: 41.9,
    lon: -93.0,
    endpoint: "https://us-central1-5tkroniexa-uc.a.run.app",
    noCors: true,
  },
  {
    id: "gcp-us-west1",
    provider: "gcp",
    city: "Oregon",
    country: "US",
    lat: 45.6,
    lon: -122.7,
    endpoint: "https://us-west1-5tkroniexa-uw.a.run.app",
    noCors: true,
  },
  {
    id: "gcp-europe-west1",
    provider: "gcp",
    city: "Belgium",
    country: "BE",
    lat: 50.4,
    lon: 3.8,
    endpoint: "https://europe-west1-5tkroniexa-ew.a.run.app",
    noCors: true,
  },
  {
    id: "gcp-europe-west2",
    provider: "gcp",
    city: "London",
    country: "GB",
    lat: 51.5,
    lon: -0.1,
    endpoint: "https://europe-west2-5tkroniexa-nw.a.run.app",
    noCors: true,
  },
  {
    id: "gcp-europe-west3",
    provider: "gcp",
    city: "Frankfurt",
    country: "DE",
    lat: 50.1,
    lon: 8.7,
    endpoint: "https://europe-west3-5tkroniexa-ey.a.run.app",
    noCors: true,
  },
  {
    id: "gcp-asia-east1",
    provider: "gcp",
    city: "Taiwan",
    country: "TW",
    lat: 25.0,
    lon: 121.6,
    endpoint: "https://asia-east1-5tkroniexa-de.a.run.app",
    noCors: true,
  },
  {
    id: "gcp-asia-northeast1",
    provider: "gcp",
    city: "Tokyo",
    country: "JP",
    lat: 35.7,
    lon: 139.7,
    endpoint: "https://asia-northeast1-5tkroniexa-an.a.run.app",
    noCors: true,
  },
  {
    id: "gcp-asia-southeast1",
    provider: "gcp",
    city: "Singapore",
    country: "SG",
    lat: 1.3,
    lon: 103.8,
    endpoint: "https://asia-southeast1-5tkroniexa-as.a.run.app",
    noCors: true,
  },
  {
    id: "gcp-australia-southeast1",
    provider: "gcp",
    city: "Sydney",
    country: "AU",
    lat: -33.9,
    lon: 151.2,
    endpoint: "https://australia-southeast1-5tkroniexa-ts.a.run.app",
    noCors: true,
  },

  // Cloudflare (anycast, nearest PoP)
  {
    id: "cf-nearest",
    provider: "cloudflare",
    city: "nearest edge",
    country: "",
    lat: 0,
    lon: 0,
    endpoint: "https://speed.cloudflare.com/__down?bytes=0",
    noCors: true,
  },
];
